#region Configuration of Jekyll

title: News of FAForever
email: promo@faforever.com
url: https://news.faforever.com
description: >-
  Provides news about the community driven lobby for Supreme Commander: Forged Alliance Forever.

permalink: /:year/:month/:day/:title:output_ext

plugins_dir: _plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-category-pages
  - jekyll-transcode-image-filters
  - jekyll-icalendar-feed
  - jekyll-sitemap

# Excluded files and folders
# Note that files that start with `_` are automatically excluded.
exclude:
  - .sass-cache/
  - .idea/
  - .vscode/
  - .gitignore
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
#endregion

#region Configuration of site globals

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

# Useful resources:
# - https://shopify.github.io/liquid/filters/date/
# - https://strftime.net/
date_format: "%d %B, %Y"
#endregion

#region Configuration of jekyll-icalendar-feed
# See also: https://github.com/Garanas/jekyll-icalendar-feed

icalendar_feed:
  categories:
    - tournament
#endregion

#region  Configuration of: jekyll-github-metadata
# See also: https://github.com/jekyll/github-metadata

repository: FAForever/website-news
#endregion

# Configuration of: jekyll-feed
# See also: https://github.com/jekyll/jekyll-feed

feed:
  path: /news/atom/index.xml
#endregion

#region Configuration of: jekyll-category-pages
# See also: https://github.com/field-theory/jekyll-category-pages

category_layout: category_index.html
category_path: category
#endregion
