name: Build

on:
  # Enable this workflow to be used by other workflows
  workflow_call:

  # Enable this workflow to be triggered manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          cache-version: 0
          working-directory: "${{ github.workspace }}/src"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Setup service worker
        run: | 
          npm install --clean
          npm run workbox-generate

      - name: Upload artifact for GitHub pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages'
          path: "src/_site/"

      - name: Upload artifact for CI
        uses: actions/upload-artifact@v4
        with:
          name: 'build'
          path: "src/_site/"
