name: Build

on:
  # Enable this workflow to be used by other workflows
  workflow_call:

  # Enable this workflow to be triggered manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          cache-version: 0
          working-directory: "${{ github.workspace }}/src"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages-build'
          path: "_site/"
