name: Continuous integration

on:
  push:
    branches-ignore: deploy/gh-pages

jobs:
  build:
    name: Create a build
    uses: ./.github/workflows/build.yaml

  lighthouse:
    # A tool to measure website performance. See also:
    # - https://github.com/GoogleChrome/lighthouse
    # - https://github.com/GoogleChrome/lighthouse-ci
    # - https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md

    name: Lighthouse
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: run Lighthouse CI
        continue-on-error: true
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: .lighthouseci
