name: Jekyll - Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src
    container: ghcr.io/garanas/website-news-jekyll-environment:0.0.1
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      # We restore images to speed up the build process

      - name: Restore cached images
        id: cache-images-restore
        uses: actions/cache@v4
        with:
          path: src/cache
          key: cache-images-${{runner.os}}-${{ hashFiles('src/assets/images/**') }}
          restore-keys: |
            cache-images-${{runner.os}}-

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # Post process the build

      - name: Upload artifact for CI
        uses: actions/upload-artifact@v4
        with:
          name: "build"
          path: "src/_site/"
