name: Jekyll - Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container: ghcr.io/garanas/website-news-jekyll-environment:0.0.1
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      # We restore images to speed up the build process

      - name: Restore cached images
        id: cache-images-restore
        uses: actions/cache/restore@v4
        with:
          path: /user/local/src/cache
          key: cache-images-${{ hashFiles('/user/local/src/assets/images/**') }}

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # We store the images to speed up the build process

      - name: Save images to cache
        if: steps.cache-images-restore.outputs.cache-hit != 'true'
        id: cache-images-save
        uses: actions/cache/save@v4
        with:
          path: user/local/src/cache
          key: ${{ steps.cache-images-restore.outputs.cache-primary-key }}

      # Post process the build

      - name: Upload artifact for CI
        uses: actions/upload-artifact@v4
        with:
          name: "build"
          path: "/user/local/src/_site/"
